name: Release Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  checks: write
  contents: read
  pull-requests: read

jobs:
  # Add any job before (e.g. build, deploy) ...

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Trigger Release Tests
        uses: aws-actions/devops-agent-qa@v1
        with:
          webhook-url: ${{ secrets.DEVOPS_AGENT_WEBHOOK_URL }}
          webhook-secret: ${{ secrets.DEVOPS_AGENT_WEBHOOK_SECRET }}
          test-profile-id: ki-05684e5b-4c19-4c81-a157-a504cbba569f
          test-requirement: "verify one api is correct"
        env:
          GITHUB_TOKEN: ${{ github.token }}

  # ... or any job after
